env:
  browser: true
  es2021: true
  jest: true
  node: true
global:
  __webpack_init_sharing__: readonly
  __webpack_share_scopes__: readonly
  strapi: readonly
extends:
  - standard-with-typescript
  - plugin:import/typescript
  - airbnb
  - airbnb/hooks
  - plugin:testing-library/recommended
  - plugin:testing-library/react
  - plugin:jest-dom/recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - prettier/react
  - prettier
parser: @typescript-eslint/parser
overrides: []
parserOptions:
  ecmaVersion: latest
  ecmaFeature:
    jsx: true
  sourceType: module
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
  - import-helpers
  - testing-library
  - jest-dom
rules: 
  semi: 'off'
  prettier/prettier:
    - error
    - printWidth: 100
      tabWidth: 2
      singleQuote: true
      trailingComma: all
      arrowParens: always
      semi: false
    - usePrettierrc: false
  no-await-in-loop: 'off'
  no-use-before-define: 'off'
  no-unused-vars: 'off'
  no-unused-expressions: 'off'
  no-useless-constructor: 'off'
  class-methods-use-this: 'off'
  arrow-body-style:
    - error
    - as-needed
  no-param-reassign: 'off'
  no-shadow: 'off'
  camelcase: 'off'
  "@typescript-eslint/no-shadow": error
  "@typescript-eslint/camelcase": 'off'
  "@typescript-eslint/interface-name-prefix": 'off'
  "@typescript-eslint/no-use-before-define": 'off'
  "@typescript-eslint/explicit-function-return-type": 'off'
  "@typescript-eslint/explicit-module-boundary-types": 'off'
  "@typescript-eslint/no-var-requires": 'off'
  "@typescript-eslint/no-explicit-any":
    - error
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: _
  "@typescript-eslint/no-empty-interface":
    - error
    - allowSingleExtends: true
  jsx-a11y/label-has-associated-control:
    - 2
    - labelComponents: []
      labelAttributes: []
      controlComponents: []
      assert: either
      depth: 3
  react/prop-types: 'off'
  react/jsx-one-expression-per-line: 'off'
  react/jsx-props-no-spreading: 'off'
  react/jsx-filename-extension:
    - warn
    - extensions:
      - ".tsx"
      - ".jsx"
  react/no-danger: 'off'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  global-require: 'off'
  import/no-dynamic-require: 'off'
  import/no-unresolved: 'off'
  import/prefer-default-export: 'off'
  import/no-duplicates: 'off'
  import/no-extraneous-dependencies: 'off'
  import/extensions:
    - error
    - ignorePackages
    - ts: never
      tsx: never
      js: never
      jsx: never
      '': never
  import-helpers/order-imports:
    - warn
    - newlinesBetween: always
      groups:
      - "/^react$/"
      - module
      - "/^@/"
      - - parent
        - sibling
        - index
      alphabetize:
        order: ignore
        ignoreCase: true
  no-underscore-dangle: 'off'
  react/require-default-props: 'off'
settings:
  "import/resolver": 
    typescript:
  react:
    version: detect
