env:
  browser: true
  es2021: true
  jest: true
extends:
  - standard-with-typescript
  - plugin:import/typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  ecmaFeature:
    jsx: true
  sourceType: module
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
rules: {}
settings:
  react:
    version: detect
